// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  root: string | undefined;
  infoWrap: string | undefined;
  titleName: string | undefined;
  statWrap: string | undefined;
  statItem: string | undefined;
  statValue: string | undefined;
  labelWrap: string | undefined;
  label: string | undefined;
  pictureWrap: string | undefined;
}
export const cssExports: CssExports;
export default cssExports;
