// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  root: string | undefined;
  contentWrap: string | object | null;
  contentText: string | undefined;
  contentParallax: string | undefined;
}
export const cssExports: CssExports;
export default cssExports;
