// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  root(root: any, className: object | null): string | undefined;
}
export const cssExports: CssExports;
export default cssExports;
