// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  root: string | undefined;
  wrap: string | undefined;
  pokemonLogo: string | undefined;
  menuWrap: string | undefined;
  menuLink(menuLink: any, arg1: { [x: number]: boolean }): string | undefined;
  activeLink: any;
}
export const cssExports: CssExports;
export default cssExports;
