// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  root: string | undefined;
  smallPokeBall: string | undefined;
  cloud: string | undefined;
  cloudBig: string | undefined;
  pokeBall: string | undefined;
  pikachu: string | undefined;
}
export const cssExports: CssExports;
export default cssExports;
