// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  wrapper(wrapper: any, arg1: { [x: number]: boolean }): string | undefined;
  isLoading: any;
  title: string | undefined;
  root: string | object | null;
}
export const cssExports: CssExports;
export default cssExports;
